### ISSUE TITLE
Generating new expert data

### ISSUE THREAD

**Issue by tha725** [YunzhuLi/InfoGAIL#7]
Could you share the code for extracting human expert data? 
Thanks for sharing the code btw.

**Comment by YunzhuLi** [comment]
Please have a look at ```torcs-1.3.4/src/drivers/human/human.cpp```, where the blocks commented with "Yunzhu" will give you some hints of how to collect the demonstrations.

**Comment by shanjgit** [comment]
Hi, @YunzhuLi  
Currently I am using your code blocks to collect data. There is no problem collecting text data. But when it comes to collecting images, the program shuts down after saving two images. The version is torcs-1.3.7 Here is the error message: 

 `OpenAL backend info:
  Vendor: OpenAL Community
  Renderer: OpenAL Soft
  Version: 1.1 ALSOFT 1.14
  Available sources: 256
  Available buffers: 1024 or more
  Dynamic Sources: requested: 235, created: 235
  #static sources: 21
  #dyn sources   : 235
Step: 0, Damage: 0.00, Dist: 1957.56, TrackPos: 0.0029, Action: 0.0063 0.1967 0.0000, SpeedX: -0.02
Step: 1, Damage: 0.00, Dist: 1957.56, TrackPos: 0.0029, Action: 0.0067 0.2007 0.0000, SpeedX: -0.02
Step: 2, Damage: 0.00, Dist: 1957.56, TrackPos: 0.0029, Action: 0.0067 0.2007 0.0000, SpeedX: -0.02

Program received signal SIGSEGV, Segmentation fault.
__memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:33
33	../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S: No such file or directory.
(gdb) #0  __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:33
#1  0x00007ffff6684c7f in png_write_row () from /lib/x86_64-linux-gnu/libpng12.so.0
#2  0x00007ffff6684ef8 in png_write_image () from /lib/x86_64-linux-gnu/libpng12.so.0
#3  0x00007ffff739563e in GfImgWritePng (img=0x0, 
    filename=filename@entry=0x7fffffffdb60 "/home/shan/link/shanjyunwu5/human_low_case_1/demo/capture-2.png", width=640, height=480) at img.cpp:266
#4  0x00007fffe256dfcf in common_drive (index=index@entry=1, car=car@entry=0x1671b10, 
    s=<optimized out>) at human.cpp:1121
#5  0x00007fffe256fb7d in drive_at (index=1, car=0x1671b10, s=<optimized out>) at human.cpp:1299
#6  0x00007ffff6f5f98b in ReOneStep (deltaTimeIncrement=deltaTimeIncrement@entry=0.002)
    at raceengine.cpp:701
#7  0x00007ffff6f5fde4 in ReUpdate () at raceengine.cpp:797
#8  0x00007ffff6f5d395 in ReStateManage () at racestate.cpp:97
#9  0x00007ffff6b27244 in ?? () from /usr/lib/x86_64-linux-gnu/libglut.so.3
#10 0x00007ffff6b2aaa9 in fgEnumWindows () from /usr/lib/x86_64-linux-gnu/libglut.so.3
#11 0x00007ffff6b277fd in glutMainLoopEvent () from /usr/lib/x86_64-linux-gnu/libglut.so.3
#12 0x00007ffff6b28065 in glutMainLoop () from /usr/lib/x86_64-linux-gnu/libglut.so.3
#13 0x0000000000401af5 in main (argc=7, argv=0x7fffffffe4a8) at main.cpp:225
(gdb) quit
A debugging session is active.

	Inferior 1 [process 12499] will be killed.
`
Have you come up with this error before? Can you give me some tips on how to solve it?

**Comment by shanjgit** [comment]
Hi, @YunzhuLi  
Currently I am using your code blocks to collect data. There is no problem collecting text data. But when it comes to collecting images, the program shuts down after saving two images. The version is torcs-1.3.7 Here is the error message: 

```
OpenAL backend info:
  Vendor: OpenAL Community
  Renderer: OpenAL Soft
  Version: 1.1 ALSOFT 1.14
  Available sources: 256
  Available buffers: 1024 or more
  Dynamic Sources: requested: 235, created: 235
  #static sources: 21
  #dyn sources   : 235
Step: 0, Damage: 0.00, Dist: 1957.56, TrackPos: 0.0029, Action: 0.0063 0.1967 0.0000, SpeedX: -0.02
Step: 1, Damage: 0.00, Dist: 1957.56, TrackPos: 0.0029, Action: 0.0067 0.2007 0.0000, SpeedX: -0.02
Step: 2, Damage: 0.00, Dist: 1957.56, TrackPos: 0.0029, Action: 0.0067 0.2007 0.0000, SpeedX: -0.02

Program received signal SIGSEGV, Segmentation fault.
__memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:33
33	../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S: No such file or directory.
(gdb) #0  __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:33
#1  0x00007ffff6684c7f in png_write_row () from /lib/x86_64-linux-gnu/libpng12.so.0
#2  0x00007ffff6684ef8 in png_write_image () from /lib/x86_64-linux-gnu/libpng12.so.0
#3  0x00007ffff739563e in GfImgWritePng (img=0x0, 
    filename=filename@entry=0x7fffffffdb60 "/home/shan/link/shanjyunwu5/human_low_case_1/demo/capture-2.png", width=640, height=480) at img.cpp:266
#4  0x00007fffe256dfcf in common_drive (index=index@entry=1, car=car@entry=0x1671b10, 
    s=<optimized out>) at human.cpp:1121
#5  0x00007fffe256fb7d in drive_at (index=1, car=0x1671b10, s=<optimized out>) at human.cpp:1299
#6  0x00007ffff6f5f98b in ReOneStep (deltaTimeIncrement=deltaTimeIncrement@entry=0.002)
    at raceengine.cpp:701
#7  0x00007ffff6f5fde4 in ReUpdate () at raceengine.cpp:797
#8  0x00007ffff6f5d395 in ReStateManage () at racestate.cpp:97
#9  0x00007ffff6b27244 in ?? () from /usr/lib/x86_64-linux-gnu/libglut.so.3
#10 0x00007ffff6b2aaa9 in fgEnumWindows () from /usr/lib/x86_64-linux-gnu/libglut.so.3
#11 0x00007ffff6b277fd in glutMainLoopEvent () from /usr/lib/x86_64-linux-gnu/libglut.so.3
#12 0x00007ffff6b28065 in glutMainLoop () from /usr/lib/x86_64-linux-gnu/libglut.so.3
#13 0x0000000000401af5 in main (argc=7, argv=0x7fffffffe4a8) at main.cpp:225
(gdb) quit
A debugging session is active.

```


 


Have you come up with this error before? Can you give me some tips on how to solve it?
